extends: existence
message: "'%s'  Use more direct language."
ignorecase: true
level: warning
tokens:
  - a number of
  - accede to
  - adjacent to
  - adversely impact
  - all things considered
  - along the lines of
  - already existing
  - as a matter of fact
  - as a means of
  - as far as I'm concerned
  - as of yet
  - as to
  - as yet
  - at the present time
  - at this time
  - because of the fact that
  - by means of
  - by virtue of
  - by virtue of the fact that
  - close proximity
  - comply with
  - due to the fact that
  - each and every
  - factual evidence
  - first and foremost
  - for all intents and purposes
  - for the most part
  - for the purpose of
  - have a tendency to
  - honest truth
  - if and when
  - in a manner of speaking
  - in a timely manner
  - in a very real sense
  - in accordance with
  - in addition
  - in all likelihood
  - in an effort to
  - in between
  - in excess of
  - in lieu of
  - in light of the fact that
  - in many cases
  - in my opinion
  - in order to
  - in regard to
  - in some instances
  - in terms of
  - in the case of
  - in the event that
  - in the final analysis
  - in the nature of
  - in the near future
  - in the process of
  - incumbent upon
  - is applicable to
  - is responsible for
  - it is essential
  - it seems that
  - it was
  - not certain
  - not many
  - not often
  - not unless
  - not unlike
  - null and void
  - on the contrary
  - on the other hand
  - one particular
  - owing to the fact that
  - pass away
  - pertaining to
  - point in time
  - portion
  - prior to
  - prioritize
  - provided that
  - put simply
  - readily apparent
  - refer back
  - should you wish
  - span across
  - so to speak
  - successfully complete
  - the month of
  - the point I am trying to make
  - time period
  - to a certain degree
  - took advantage of
  - until such time as
  - utilization
  - utilize
  - various different
  - what I mean to say is
  - whether or not
  - with respect to
  - with the exception of
  - would argue that
  - increasingly less
  - advancing backwards
  - alludes explicitly to
  - explicitly alludes to
  - totally obsolete
  - completely obsolete
  - generally always
  - usually always
  - increasingly less
  - build down
  - conspicuous absence
  - exact estimate
  - found missing
  - intense apathy
  - mandatory choice
  - organized mess
