extends: existence
message: "Use simpler words instead of '%s'."
ignorecase: true
level: warning
tokens:
  - abundance
  - accelerate
  - accentuate
  - accompany
  - accomplish
  - accorded
  - accrue
  - acquiesce
  - acquire
  - adjustment
  - admissible
  - advantageous
  - advise
  - aforementioned
  - aggregate
  - alleviate
  - allocate
  - ameliorate
  - anticipate
  - apparent
  - appreciable
  - ascertain
  - assistance
  - attain
  - authorize
  - belated
  - bestow
  - cease
  - commence
  - concerning
  - consequently
  - constitutes
  - demonstrate
  - depart
  - designate
  - discontinue
  - economical
  - eliminate
  - elucidate
  - employ
  - endeavor
  - equitable
  - equivalent
  - evidenced
  - exclusively
  - expedite
  - expend
  - expiration
  - facilitate
  - feasible
  - forfeit
  - formulate
  - however
  - impacted
  - implement
  - inception
  - indicate
  - indication
  - initiate
  - irregardless
  - magnitude
  - methodology
  - monitor
  - necessitate
  - nevertheless
  - notwithstanding
  - numerous
  - objective
  - obligate
  - obtain
  - optimum
  - overall
  - participate
  - particulars
  - portion
  - possess
  - preclude
  - prioritize
  - procure
  - proficiency
  - purchase
  - regarding
  - relocate
  - remainder
  - remuneration
  - reside
  - residence
  - retain
  - satisfy
  - shall
  - solicit
  - strategize
  - subsequent
  - substantial
  - sufficient
  - terminate
  - therefore
  - transpire
  - utilization
  - utilize
  - validate
  - witnessed
  - decimate
  - effete
  - fulsome
  - impassionate
