version: "2"

services:
  drupal:
    build: .
    image: rkoron/custom-drupal
    ports:
      - "8080:80"
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      # now everytime we boot up compose we will have the
      # same password and data available to us
      - drupal-data:/var/lib/postgresql/data
volumes:
  drupal-data:
